package vista;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import vista.InicioEmp;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import controlador.ConexionBD;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import modelo.EmpleadoDAO;
import modelo.EmpleadoDTO;
import modelo.TiendaDAO;
import modelo.UsuarioDAO;
import modelo.UsuarioDTO;
import vista.InicioEmp;

public class RegistrarAdm extends javax.swing.JFrame {
    private static final String EMPTY_FIELDS_MESSAGE = "No puede dejar los campos vacíos.";
    private static final String INCORRECT_CREDENTIALS_MESSAGE = "Usuario o contraseña incorrectos";
    private static final String USERNAME_EMPTY_MESSAGE = "El nombre de usuario no puede estar vacío.";
    private static final String PASSWORD_EMPTY_MESSAGE = "La contraseña no puede estar vacía.";
    private static final int MIN_USERNAME_LENGTH = 4;
    private static final int MIN_PASSWORD_LENGTH = 6;
    private static final int MAX_LENGTH = 10;
    
    private void cargarIdsTiendas() {
    TiendaDAO tiendaDAO = new TiendaDAO();
    List<String> idsTiendas = tiendaDAO.cargarNombresTiendas();
    
    for (String id : idsTiendas) {
        cbxIdTiendaEmpleado.addItem(id); // Añadir cada nombre de tienda al JComboBox
    }
}
    
    private void cargarIdsUsuarios() {
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    List<String> idsUsuarios = usuarioDAO.cargarNombresUsuarios();

    for (String id : idsUsuarios) {
        cbxIdUsuarioEmpleado.addItem(id); 
    }
}

    
    public RegistrarAdm() {
        initComponents();
        cargarIdsTiendas();
        cargarIdsUsuarios();
        this.setLocationRelativeTo(this);
        this.setTitle("Registrar empleados y usuarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private boolean validateInputs() {
    String username = txtUsuarioEmpleado.getText().trim();
    String password = String.valueOf(txtContraUsuario.getPassword()).trim();

    if (username.isEmpty()) {
        JOptionPane.showMessageDialog(this, USERNAME_EMPTY_MESSAGE, "Error", JOptionPane.ERROR_MESSAGE);
        txtUsuarioEmpleado.requestFocus();
        return false;
    }
    if (username.length() < MIN_USERNAME_LENGTH) {
        JOptionPane.showMessageDialog(this, "El nombre de usuario debe tener al menos " + MIN_USERNAME_LENGTH + " caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
        txtUsuarioEmpleado.requestFocus();
        return false;
    }
    if (username.length() > MAX_LENGTH) {
        JOptionPane.showMessageDialog(this, "El nombre de usuario no puede tener más de " + MAX_LENGTH + " caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
        txtUsuarioEmpleado.requestFocus();
        return false;
    }
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, PASSWORD_EMPTY_MESSAGE, "Error", JOptionPane.ERROR_MESSAGE);
        txtContraUsuario.requestFocus();
        return false;
    }
    if (password.length() < MIN_PASSWORD_LENGTH) {
        JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos " + MIN_PASSWORD_LENGTH + " caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
        txtContraUsuario.requestFocus();
        return false;
    }
    if (password.length() > MAX_LENGTH) {
        JOptionPane.showMessageDialog(this, "La contraseña no puede tener más de " + MAX_LENGTH + " caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
        txtContraUsuario.requestFocus();
        return false;
    }
    return true;
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuarioEmpleado = new javax.swing.JTextField();
        btnRegistrarUsuarioEmpleado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtApellidoEmpleado = new javax.swing.JTextField();
        cbxIdTiendaEmpleado = new javax.swing.JComboBox<>();
        cbxIdUsuarioEmpleado = new javax.swing.JComboBox<>();
        btnRegistrarInformacionUsuarioEmpleado = new javax.swing.JButton();
        txtContraUsuario = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inicio/");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("Registrar");

        jLabel3.setText("Ingreso de datos de Usuarios Empleados");

        jLabel4.setText("Ingrese usuario");

        jLabel5.setText("Ingrese contraseña");

        btnRegistrarUsuarioEmpleado.setText("Registrar");
        btnRegistrarUsuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUsuarioEmpleadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Ingresa nombre");

        jLabel7.setText("Ingresa apellido");

        jLabel8.setText("Elija sede de la tienda");

        jLabel9.setText("Elija al usuario");

        jLabel10.setText("Ingreso de datos de Empleados");

        cbxIdTiendaEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));

        cbxIdUsuarioEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--" }));

        btnRegistrarInformacionUsuarioEmpleado.setText("Registrar");
        btnRegistrarInformacionUsuarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarInformacionUsuarioEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRegistrarInformacionUsuarioEmpleado)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel5))
                                            .addGap(98, 98, 98)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cbxIdUsuarioEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxIdTiendaEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtApellidoEmpleado)
                                                .addComponent(txtNombreEmpleado)
                                                .addComponent(txtContraUsuario)
                                                .addComponent(txtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel3))
                                    .addGap(38, 38, 38)
                                    .addComponent(btnRegistrarUsuarioEmpleado)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel10)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnRegistrarUsuarioEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtContraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addComponent(btnRegistrarInformacionUsuarioEmpleado)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxIdTiendaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbxIdUsuarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarInformacionUsuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarInformacionUsuarioEmpleadoActionPerformed
    
        // Obtener los valores de los campos de texto y ComboBox
    String nombreEmpleado = txtNombreEmpleado.getText();
    String apellidoEmpleado = txtApellidoEmpleado.getText();
    String idTiendaEmpleado = (String) cbxIdTiendaEmpleado.getSelectedItem(); // ID de tienda seleccionado
    String idUsuarioEmpleado = (String) cbxIdUsuarioEmpleado.getSelectedItem(); // ID de usuario seleccionado

    // Comprobar que los campos no estén vacíos
    if (nombreEmpleado.isEmpty() || apellidoEmpleado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (idTiendaEmpleado== "--Seleccionar--" || idUsuarioEmpleado == "--Seleccionar--") {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una opción válida.", "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    
    
    TiendaDAO tiendaDAO = new TiendaDAO();
    int idTienda = tiendaDAO.obtenerIdTiendaPorNombre(idTiendaEmpleado);
    
    
    UsuarioDAO usuarioDAO = new UsuarioDAO();
    int idUsuario = usuarioDAO.obtenerIdUsuarioPorNombre(idUsuarioEmpleado);
        
     EmpleadoDAO controlador = new EmpleadoDAO();
     if (idTienda != -1 && idUsuario != -1) {
            // Llamar al método registrarEmpleado
            EmpleadoDTO nuevoEmpleado = controlador.registrarEmpleado(
                nombreEmpleado,
                apellidoEmpleado,
                idTienda,
                idUsuario
            );

            // Mostrar el resultado
            if (nuevoEmpleado != null) {
                JOptionPane.showMessageDialog(this, "Empleado registrado exitosamente!");
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el empleado.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tienda o Usuario no encontrado.");
        }
    
    
    
    
    
    
    
    }//GEN-LAST:event_btnRegistrarInformacionUsuarioEmpleadoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    InicioAdm objInicio = new InicioAdm();
    objInicio.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnRegistrarUsuarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUsuarioEmpleadoActionPerformed
    if (!validateInputs()) return;
    String usuario_empleado = txtUsuarioEmpleado.getText().trim();
    String contrasena_empleado = txtContraUsuario.getText().trim(); 

    // Validar que los campos no estén vacíos
    if (usuario_empleado.isEmpty() || contrasena_empleado.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear instancia del DAO
    UsuarioDAO usuarioDAO = new UsuarioDAO();

    // Llamar al método para registrar al empleado
    UsuarioDTO nuevoEmpleado = usuarioDAO.registrarEmpleado(usuario_empleado, contrasena_empleado, "emple");

    // Verificar si el registro fue exitoso
    if (nuevoEmpleado != null) {
        JOptionPane.showMessageDialog(this, "Empleado registrado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        // Opcional: Limpiar los campos después de un registro exitoso
        txtUsuarioEmpleado.setText("");
        txtContraUsuario.setText("");
        // Actualizar el ComboBox
    actualizarComboBoxUsuarios();
    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar el empleado. Intente nuevamente.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    
    
    }//GEN-LAST:event_btnRegistrarUsuarioEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void actualizarComboBoxUsuarios() {
      // Cargar los nombres de los usuarios desde la base de datos
    List<String> nombresUsuarios = new UsuarioDAO().cargarNombresUsuarios();

    // Crear una nueva lista que incluya el valor "--Seleccionar--" al principio
    List<String> listaUsuariosConSeleccion = new ArrayList<>();
    listaUsuariosConSeleccion.add("--Seleccionar--");  // Agregar la opción de selección

    // Agregar los nombres de los usuarios a la lista
    listaUsuariosConSeleccion.addAll(nombresUsuarios);

    // Crear el modelo para el JComboBox con la nueva lista
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listaUsuariosConSeleccion.toArray(new String[0]));

    // Establecer el modelo actualizado en el JComboBox
    cbxIdUsuarioEmpleado.setModel(model);
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarInformacionUsuarioEmpleado;
    private javax.swing.JButton btnRegistrarUsuarioEmpleado;
    private javax.swing.JComboBox<String> cbxIdTiendaEmpleado;
    private javax.swing.JComboBox<String> cbxIdUsuarioEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidoEmpleado;
    private javax.swing.JPasswordField txtContraUsuario;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
